### ISSUE TITLE
Check Bug:

### ISSUE THREAD

**Issue by MelissaMc20** [Code-Operative/Reuse#67] opened 2021-06-23 10:17 UTC
3 Charities have registered and for some reason all of their data has changed to 'The Ellis Charity' - '123 Charity Number' and Collection postcode and delivery postcode - these all match a test shop that ellis had set up and is now deleted. 
See Screenshot

**Comment by MelissaMc20** [comment] 2021-06-23 10:17
![image](https://user-images.githubusercontent.com/59023121/123080207-9a69ee00-d414-11eb-98a3-328636a2e3b1.png)

Mel: I've tried to recreate bug but didn't happen

**Comment by kyeap** [comment] 2021-06-23 20:56
It seems that this only happens to the customize field details and not other details in the frontend. Looking at the database, it seems that the information in the seller table are also missing e.g. phone number and business email, they have the value of null in the DB. 

After further investigation (there was a duplicate of the DB prior to this incident) it is found that `ps_kb_mp_custom_field_seller_mapping` already had the seller_id 29,30,31 - the id of the first seller who has this problem, hence when seller_id 29,30,31 was created they had problems inserting their data into the table, presumably because there was a transactional query that failed trying to create a duplicate in the `ps_kb_mp_custom_field_seller_mapping` table. 

I don't think this will be happening again in the future, because we can't recreate the error in new seller registration. This is because the new seller registration is getting seller_id that the ps_kb_mp_custom_field_seller_mapping does not yet have. 

Still unclear: 
- it seems that the seller_id and customer_id got mixed up in various areas, compare `psrn_kn_mp_seller` and also `ps_kb_mp_custom_field_seller_mapping`
- in fact `ps_kb_mp_custom_field_seller_mapping` have multiple combinations of customer and seller id
- seller_id 32 seems to be affected as well 
- the details in `ps_kb_mp_custom_field_seller_mapping` has a timestamp on the date_upd column on the 11/6 for the cus_id 44 and seller_id 29 both of which did not yet exist then - how then is this change made? 

Further information: 
This error is observed when trying to register the seller 29 on the development server with the duplicate DB with debug mode on. 
![image](https://user-images.githubusercontent.com/39419492/123157415-674e4b80-d462-11eb-842c-717debf79c8a.png)

**Closed** 2021-06-30 13:35 UTC
